# Generated by Django 2.2.6 on 2019-10-08 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191008_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='suburb',
            field=models.CharField(max_length=254, validators=[django.core.validators.RegexValidator(message='invalid postal code', regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
