# Generated by Django 2.2.6 on 2019-10-08 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191008_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='postcode',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='invalid postal code', regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='suburb',
            field=models.CharField(max_length=254),
        ),
    ]
