# Generated by Django 2.0.13 on 2019-10-08 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191008_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='postcode',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='invalid postal code', regex='^\\+?1?\\d{0,10}$')]),
        ),
    ]
